# Generated by Django 6.0.3 on 2026-03-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(db_column='model', max_length=200),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='model_name',
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_oversold',
            field=models.BooleanField(default=False, verbose_name='Allow Overselling'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Warehouse Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_alert_quantity',
            field=models.IntegerField(default=5, verbose_name='Low Stock Threshold'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suggested_selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Suggested Selling Price'),
        ),
    ]
