# Generated by Django 6.0.3 on 2026-03-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_options_alter_product_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Profit Margin (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suggested_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Suggested Selling Price'),
        ),
    ]
