# Generated by Django 6.0.3 on 2026-03-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_profit_margin_percentage_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE inventory_product DROP COLUMN IF EXISTS barcode;"
                        "ALTER TABLE inventory_product DROP COLUMN IF EXISTS color;"
                        "ALTER TABLE inventory_product DROP COLUMN IF EXISTS image;"
                        "ALTER TABLE inventory_product DROP COLUMN IF EXISTS size;"
                        "ALTER TABLE inventory_product DROP COLUMN IF EXISTS sku;"
                        "ALTER TABLE inventory_stock DROP COLUMN IF EXISTS product_id;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(model_name='product', name='barcode'),
                migrations.RemoveField(model_name='product', name='color'),
                migrations.RemoveField(model_name='product', name='image'),
                migrations.RemoveField(model_name='product', name='size'),
                migrations.RemoveField(model_name='product', name='sku'),
                migrations.RemoveField(model_name='stock', name='product'),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='can_be_oversold',
            field=models.BooleanField(default=False, verbose_name='Allow Overselling'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Warehouse Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_alert_quantity',
            field=models.IntegerField(default=5, verbose_name='Low Stock Threshold'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Profit Margin (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suggested_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Suggested Selling Price'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        # Create ProductVariant table if it doesn't exist yet.
                        "CREATE TABLE IF NOT EXISTS inventory_productvariant ("
                        "id BIGSERIAL PRIMARY KEY, "
                        "sku VARCHAR(100) UNIQUE NOT NULL, "
                        "size VARCHAR(50) NOT NULL, "
                        "color VARCHAR(100) NOT NULL, "
                        "image VARCHAR(100) NULL, "
                        "product_id BIGINT NOT NULL "
                        ");"
                        # Ensure FK exists (if not already).
                        "DO $$ BEGIN "
                        "IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'inventory_productvariant_product_id_fkey') THEN "
                        "ALTER TABLE inventory_productvariant "
                        "ADD CONSTRAINT inventory_productvariant_product_id_fkey "
                        "FOREIGN KEY (product_id) REFERENCES inventory_product(id) ON DELETE CASCADE; "
                        "END IF; "
                        "END $$;"
                        # Add stock.variant_id if missing.
                        "ALTER TABLE inventory_stock ADD COLUMN IF NOT EXISTS variant_id BIGINT;"
                        # Ensure OneToOne-like uniqueness.
                        "DO $$ BEGIN "
                        "IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'inventory_stock_variant_id_key') THEN "
                        "ALTER TABLE inventory_stock ADD CONSTRAINT inventory_stock_variant_id_key UNIQUE (variant_id); "
                        "END IF; "
                        "END $$;"
                        # Ensure FK exists.
                        "DO $$ BEGIN "
                        "IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'inventory_stock_variant_id_fkey') THEN "
                        "ALTER TABLE inventory_stock "
                        "ADD CONSTRAINT inventory_stock_variant_id_fkey "
                        "FOREIGN KEY (variant_id) REFERENCES inventory_productvariant(id) ON DELETE CASCADE; "
                        "END IF; "
                        "END $$;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ProductVariant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('sku', models.CharField(max_length=100, unique=True)),
                        ('size', models.CharField(max_length=50)),
                        ('color', models.CharField(max_length=100)),
                        ('image', models.ImageField(blank=True, null=True, upload_to='variants/', verbose_name='Variant Image')),
                        ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
                    ],
                ),
                migrations.AddField(
                    model_name='stock',
                    name='variant',
                    field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.productvariant'),
                    preserve_default=False,
                ),
            ],
        ),
    ]
