# Generated by Django 6.0.3 on 2026-03-27 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_barcode_remove_product_color_and_more'),
        ('settings_app', '0002_product_variant_spec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'color', 'size']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='settings_app.season'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Base SKU for the product. Variants append sku_suffix to build full SKU.', max_length=100),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="If set, overrides product's suggested_selling_price for this variant", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku_suffix',
            field=models.CharField(default='', help_text="Appended to product SKU. e.g. '-BLK-M' → full SKU: 'GG-001-BLK-M'", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'sku_suffix')},
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
    ]
