# Generated by Django 6.0.3 on 2026-03-27

from django.db import migrations


def backfill_product_sku_and_variant_suffix(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    ProductVariant = apps.get_model('inventory', 'ProductVariant')

    # Ensure every product has a base SKU and every variant has a sku_suffix.
    for product in Product.objects.all().only('id', 'sku'):
        if not product.sku:
            product.sku = f"PROD-{product.id}"
            product.save(update_fields=['sku'])

    # sku_suffix is required by the new unique_together(product, sku_suffix).
    # If duplicates exist (e.g. multiple variants with ''), make them unique.
    for product in Product.objects.all().only('id'):
        variants = list(ProductVariant.objects.filter(product_id=product.id).only('id', 'sku_suffix'))
        seen = set()
        for v in variants:
            suffix = (v.sku_suffix or '').strip()
            if suffix in seen:
                # Deterministic suffix to avoid collisions.
                suffix = f"-V{v.id}"
            if suffix != v.sku_suffix:
                v.sku_suffix = suffix
                v.save(update_fields=['sku_suffix'])
            seen.add(v.sku_suffix)


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0005_product_variant_spec'),
    ]

    operations = [
        migrations.RunPython(backfill_product_sku_and_variant_suffix, migrations.RunPython.noop),
    ]

