# Generated by Django 5.2.12 on 2026-08-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_profile_permissions_alter_profile_role_and_more'),
        ('inventory', '0007_align_created_at_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.company'),
        ),
    ]
