# Generated by Django 4.2.30 on 2026-09-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_image_productvariant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
