# Generated by Django 6.0.3 on 2026-03-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_barcode_remove_product_color_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE purchases_purchaseorderitem DROP COLUMN IF EXISTS product_id;",
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='purchaseorderitem',
                    name='product',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE purchases_purchaseorderitem "
                        "ADD COLUMN IF NOT EXISTS variant_id BIGINT NULL;"
                        "DO $$ BEGIN "
                        "IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'purchases_purchaseorderitem_variant_id_fkey') THEN "
                        "ALTER TABLE purchases_purchaseorderitem "
                        "ADD CONSTRAINT purchases_purchaseorderitem_variant_id_fkey "
                        "FOREIGN KEY (variant_id) REFERENCES inventory_productvariant(id) ON DELETE RESTRICT; "
                        "END IF; "
                        "END $$;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='purchaseorderitem',
                    name='variant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant'),
                ),
            ],
        ),
    ]
