# Generated by Django 6.0.3 on 2026-04-03 00:38

import django.db.models.deletion
from django.db import migrations, models


def assign_default_category(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    Expense = apps.get_model('expenses', 'Expense')
    default_cat, _ = ExpenseCategory.objects.get_or_create(
        name='General',
        defaults={'description': 'Default category — created during migration'}
    )
    Expense.objects.filter(expense_category__isnull=True).update(
        expense_category=default_cat
    )

class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensecategory_remove_expense_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_old',
        ),
        migrations.RunPython(assign_default_category, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='expenses',
                to='expenses.expensecategory',
            ),
        ),
    ]
