# Generated by Django 6.0.3 on 2026-04-03 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensecategory_remove_expense_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category_old',
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory'),
        ),
    ]
