# Generated by Django 5.2.12 on 2026-08-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_profile_permissions_alter_profile_role_and_more'),
        ('expenses', '0003_remove_expense_category_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='accounts.company'),
        ),
    ]
