# Generated by Django 6.0.3 on 2026-03-27 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('season_type', models.CharField(choices=[('SS', 'Spring/Summer'), ('FW', 'Fall/Winter'), ('RST', 'Resort'), ('PRE', 'Pre-Collection')], max_length=4)),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', 'season_type'],
            },
        ),
        migrations.AddField(
            model_name='customertype',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-applied discount percentage for this customer type (0–100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='commercial_registration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commercial Registration Number'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='tax_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Registration Number'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Examples: +201001234567, 01001234567', regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')]),
        ),
    ]
