# Generated by Django 4.2.30 on 2026-09-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_brand_company_category_company_currency_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='base_currency_code',
            field=models.CharField(default='EGP', help_text='Base store currency for calculations', max_length=10),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='is_tax_enabled',
            field=models.BooleanField(default=True, help_text='Global VAT active / inactive toggle'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='last_rates_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='tax_rate_percentage',
            field=models.DecimalField(decimal_places=2, default=14.0, help_text='Default VAT percentage (e.g. 14 for 14%)', max_digits=5),
        ),
    ]
