# Generated by Django 6.0.3 on 2026-03-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_variant_spec'),
        ('sales', '0002_remove_salesitem_product_salesitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
    ]
