# Generated by Django 5.2.12 on 2026-08-31 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salestransaction_company'),
        ('settings_app', '0003_brand_company_category_company_currency_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.taxrate'),
        ),
    ]
